- hosts: jenkins
  # gather_facts は host 情報の読み込みの有無の設定.
  gather_facts: true
  remote_user: vagrant
  # sudo は廃止.
  become: yes
  roles:
    - apache2
    - jenkins
  handlers:
    - name: restart jenkins
      service: name=httpd state=restarted
